# Generated by Django 3.2.18 on 2024-07-26 17:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gescoo_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('decoupage', models.CharField(choices=[('Trimestre', 'Trimestre'), ('Semestre', 'Semestre')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.user')),
                ('status', models.CharField(choices=[('Affecté(e)', 'Affecté(e)'), ('Non affecté(e)', 'Non affecté(e)')], max_length=50)),
            ],
            options={
                'verbose_name': 'Eleve',
                'verbose_name_plural': 'Eleves',
            },
            bases=('gescoo_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePAT',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.user')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('gescoo_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuivieEleve',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('detail', models.FloatField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.eleve')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='PAT',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.typepat')),
            ],
            options={
                'verbose_name': 'PAT',
                'verbose_name_plural': 'PATs',
            },
            bases=('gescoo_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.typeparent')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
            bases=('gescoo_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('serie', models.ManyToManyField(blank=True, to='pedagogie.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataire', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('niveau', models.ManyToManyField(blank=True, to='pedagogie.Niveau')),
                ('serie', models.ManyToManyField(blank=True, to='pedagogie.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Lv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('handicape', models.BooleanField(default=False)),
                ('detail_handicape', models.CharField(blank=True, max_length=50, null=True)),
                ('eps', models.BooleanField(default=True)),
                ('rabais_frais_inscription', models.IntegerField()),
                ('rabais_frais_scolarite', models.IntegerField()),
                ('rabais_frais_annexe', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_inscription', to='pedagogie.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.eleve')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('note', models.IntegerField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve_evaluation', to='pedagogie.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_evaluation', to='pedagogie.matiere')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.user')),
                ('classe', models.ManyToManyField(to='pedagogie.Classe')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.grade')),
                ('matiere', models.ManyToManyField(to='pedagogie.Matiere')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
            bases=('gescoo_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='lv2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogie.lv2'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ManyToManyField(to='pedagogie.Parent'),
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('budget', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_ecole', to='gescoo_app.budget')),
                ('niveaux', models.ManyToManyField(to='pedagogie.Niveau')),
                ('series', models.ManyToManyField(to='pedagogie.Serie')),
                ('type_enseignement', models.ManyToManyField(to='pedagogie.TypeEnseignement')),
            ],
        ),
        migrations.CreateModel(
            name='DossierScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve_dossier_scolaire', to='pedagogie.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_cour', to='pedagogie.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_cour', to='pedagogie.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_cour', to='pedagogie.matiere')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='CoefficientMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.niveau')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.serie')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.serie'),
        ),
        migrations.AddField(
            model_name='classe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.typeenseignement'),
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_decoupage', models.IntegerField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_annee_scolaire', to='pedagogie.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='pedagogie.eleve')),
            ],
        ),
    ]
