# Generated by Django 3.2.18 on 2024-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ManyToManyField(to='pedagogie.Niveau'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='serie',
            field=models.ManyToManyField(to='pedagogie.Serie'),
        ),
    ]
