# Generated by Django 3.2.18 on 2024-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_auto_20240726_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ManyToManyField(blank=True, to='pedagogie.Niveau'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='serie',
            field=models.ManyToManyField(blank=True, to='pedagogie.Serie'),
        ),
    ]
