# Generated by Django 3.2.18 on 2024-07-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gescoo_app', '0001_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('montant', models.IntegerField()),
                ('raison', models.TextField()),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('montant_restant', models.IntegerField()),
                ('inscription_versement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_versement', to='pedagogie.inscription')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_versement', to='comptabilite.typepaiement')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.enseignant')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.pat')),
            ],
            bases=('gescoo_app.evenement',),
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montaint', models.IntegerField()),
                ('niveau', models.ManyToManyField(to='pedagogie.Niveau')),
                ('serie', models.ManyToManyField(to='pedagogie.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('niveau', models.ManyToManyField(to='pedagogie.Niveau')),
                ('serie', models.ManyToManyField(to='pedagogie.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='FraisAnnexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montaint', models.IntegerField()),
                ('niveau', models.ManyToManyField(to='pedagogie.Niveau')),
                ('serie', models.ManyToManyField(to='pedagogie.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gescoo_app.evenement')),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Vacataire', 'Vacataire'), ('Stagiaire', 'Stagiaire'), ('Contractuel', 'Contractuel'), ('Autre', 'Autre')], max_length=50)),
                ('salaire', models.IntegerField()),
                ('enseignant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogie.enseignant')),
                ('pat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogie.pat')),
            ],
            bases=('gescoo_app.evenement',),
        ),
    ]
